version: 0.2

phases:
  build:
    commands:
      - mvn clean 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/forex-service-0.0.1-SNAPSHOT.jar forex-service-0.0.1-SNAPSHOT.jar
artifacts:
   files:
      - forex-service-0.0.1-SNAPSHOT.jar